### ISSUE TITLE
feat: handle EIP4844 "Shard" transactions

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1005]
### Describe the Feature Request

Dencun is coming fast! We need to support new opcodes, and tx types
https://blog.ethereum.org/2024/01/10/goerli-dencun-announcement

### Describe Preferred Solution

For now, recognize when 4844 txs are sent to the network, and gracefully fail
https://eips.ethereum.org/EIPS/eip-4844

**Comment by gerceboss** [comment]
I am new to this repository, can you locate me where the blocks are identified and validated ?
