### ISSUE TITLE
feat: optimize RLP decode

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1091]
### Describe the Feature Request

1. Add some more real tx that costs a lot
2. Fund bottlenecks with `profile-cairo`
3. Optimize

### Related Code

https://github.com/kkrt-labs/kakarot/blob/main/tests/utils/constants.py
https://github.com/kkrt-labs/kakarot/blob/main/tests/src/utils/test_rlp.py

### If the feature request is approved, would you be willing to submit a PR? Yes

/ No _(Help can be provided if you need assistance submitting a PR)_

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/1092
```

**Comment by enitrat** [comment]
Not a lot of optimisations possible besides replacing is_le(a,b) by is_nn(b-a) - which is not that impactful.

<img width="507" alt="image" src="https://github.com/kkrt-labs/kakarot/assets/60658558/b4475c42-fab4-45f1-998c-ff4f07e704fc">
