### ISSUE TITLE
dev: do all call restriction checks (only owner etc.) in contracts

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1094]
In a lot of places, we currently do in the contract

```
@external
func foo{
    syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr
}(bar: felt) {
    return Library.foo(bar);
}
```

and in the associated library

```
func foo{
    syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr
}(bar: felt) {
    Ownable.assert_only_owner();
    // ...
}
```

The check `Ownable.assert_only_owner();` shouldn't be in the library because it belongs to a contract logic (who is the caller) and not a library logic (what is the function actually doing).

This issue is consequently about moving all these checks (not only only_owner but similar semantic) at the contract level

**Comment by emilamaj** [comment]
Do you mind assigning it to me ?

**Comment by stevencartavia** [comment]
Hi, can I try this one?

**Comment by enitrat** [comment]
@stevencartavia how are things going?
