### ISSUE TITLE
dev: .env variable `STARKNET_NETWORK` from "production" deployment should not collide with `make test-end-to-end` `STARKNET_NETWORK` 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1100]
.env variable `STARKNET_NETWORK` from "production" deployment should not collide with `make test-end-to-end` `STARKNET_NETWORK` 

currently in .env file, the variable STARKNET_NETWORK is used to both:
- decide on which network to deploy kakarot (potentially in production)
- decide on which network to run the integration tests 

although this allows for customizability of integration tests, this creates possibility for a dev that just deployed kakarot to prod to run the integration tests on a live network

proposed fix:
- make test-end-to-end forces STARKNET_NETWORK to be katana
- if a dev should want to run the integration tests in prod (quite nice idea to do), they can run the command manually: `poetry run pytest tests/end_to_end` knowing that Kakarot is already deployed (deployments file are committed in main for prod)

**Comment by jaipaljadeja** [comment]
Hey i would like to work on this, if its up for grabs. i believe we have to modify the Makefile where i can explicitly add `STARKNET_NETWORK=katana` when running make test-end-to-end

**Comment by Eikix** [comment]
Let's go:))!

**Comment by ClementWalter** [comment]
I don't understand the need for this issue. Tests are designed to be run against any RPC, katana, sepolia, mainnet why not. I don't think the `make` command should bring any limitation to this. The flow I understand where there could be a mistake is

```
export STARKNET_NETWORK=mainnet
make deploy
make test
```

and this looks quite explicit to me

**Comment by Eikix** [comment]
> I don't understand the need for this issue. Tests are designed to be run against any RPC, katana, sepolia, mainnet why not. I don't think the `make` command should bring any limitation to this. The flow I understand where there could be a mistake is
> 
> ```
> export STARKNET_NETWORK=mainnet
> make deploy
> make test
> ```
> 
> and this looks quite explicit to me

Usually the STARKNET_NETWORK variable is set in the .env file.
Tests are usually expected to run against a devnet, not a testnet or mainnet. Running an integration testnet suite against testnet/mainnet should be an exception

Example:
1. Dev does a mainnet deployment on day N, sets .env variable `STARKNET_NETWORK` to `kakarot-sepolia`
2. A few days pass and commits are made
3. Dev later runs `make test-end-to-end`
4. -> Kakarot is upgraded in production due to deploy script logic in production as a side effect
5. Private key spends resources to run tests

**Comment by ClementWalter** [comment]
If this is the issue, I'd rather remove the STARKNET_NETWORK from the `.env` and add the default `katana` value in the `getenv` in `kakarot_scripts/constants.py`

**Comment by Eikix** [comment]
Alright @jaipaljadeja you can now:
1. delete STARKNET_NETWORK from .env.example 
2. replace in kakarot_scripts/constants.py
```python

if os.getenv("STARKNET_NETWORK") is not None:
    if NETWORKS.get(os.environ["STARKNET_NETWORK"]) is not None:
        NETWORK = NETWORKS[os.environ["STARKNET_NETWORK"]]
    else:
        raise ValueError(
            f"STARKNET_NETWORK {os.environ['STARKNET_NETWORK']} given in env variable unknown"
        )
else:
    NETWORK = {
        "name": os.getenv("RPC_NAME", "custom-rpc"),
        "rpc_url": os.getenv("RPC_URL"),
        "explorer_url": "",
        "devnet": False,
        "check_interval": float(os.getenv("CHECK_INTERVAL", 0.1)),
        "max_wait": float(os.getenv("MAX_WAIT", 30)),
    }
```

Replace the else branch with `NETWORK = NETWORKS["katana"]]`
i.e. that the default behaviour is to use devnet when STARKNET_NETWORK variable is not set.


Please document this in the README so users can advise

**Comment by jaipaljadeja** [comment]
@Eikix may i know what exactly you want me to update in readme? sorry, i am a bit confused as to me it seems like the current `deploy` section in readme seems good to me. please correct me if i am wrong.

**Comment by Eikix** [comment]
> @Eikix may i know what exactly you want me to update in readme? sorry, i am a bit confused as to me it seems like the current `Deploy` section in readme looks good to me. please correct me if i am wrong.

My bad you're right! Readme is fine as it is

**Comment by jaipaljadeja** [comment]
just pushed the updated changes to my PR : )
