### ISSUE TITLE
bug: wrong gas estimate on Kakarot 🤔  

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#1133]
### Kakarot version

2a38051af5e69c07b02adab75353bf7ff3b952e4

### Current behavior

We are getting the wrong gas estimate for a transaction, which is resulting in the transaction failing as it is consuming all the gas.

### Expected behavior

The transaction should pass!

### Steps to reproduce
- `git clone git@github.com:Karrot-Works/on-chain-whitelist.git`
- `cd on-chain-whitelist && bun install`
-  run anvil
-  make `SEPOLIA_RPC_URL=http://127.0.0.1:8545`
-  run `bun run script/deploy.ts`
-  run `bun run scripts/mint_and_use_faucet.ts`

You will see the transaction will pass! and the script will log as estimated gas to be **97444n**.
![image](https://github.com/kkrt-labs/kakarot/assets/41180869/54ca7619-ef72-4844-b9c0-9c360dd5b851)

Now, run Katana instance via docker, make sure Kakarot is live on http://localhost:3030 via Katana.

Now, if we change `SEPOLIA_RPC_URL=http://127.0.0.1:3030` and
-  `rm data/deployments.json`
-  run `bun run script/deploy.ts`
-  run `bun run scripts/mint_and_use_faucet.ts`

We will see the transaction for the faucet's claim function will fail, and the gas estimation will be **95326n**, which is wrong and hence the whole gas is being used during the transaction!

**Comment by enitrat** [comment]
The RPC can call `eth_estimate_gas` to get the values of `required_gas` (gas_used + refund). But that is not the _actual required gas_, as there might be extra gas required to successfully execute calls (we can only pass 63/64 of the remaining gas to the call).
As such, once the RPC knows the gas_used + refund, it should compute the minimum required gas to execute the transaction. 

Major clients implement a binary search to find the minimum acceptable value.
