### ISSUE TITLE
feat: add whitelisted mechanism for pre-eip155 addresses

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1151]
### Describe the Feature Request

For now, everyone can send pre-eip155 transactions, that don't sign the chainID of the transaction. We need to whitelist only specific addresses (e.g. Kakarot owner) to be able to send these transactions, to prevent replay attacks.

### Solution
 - Add a storage var map(tx_hash, whitelisted)
 - During validation of pre-eip155 tx, load the whitelist for this transaction
 - if it's whitelisted, pass-through - otherwise, reject

**Comment by elielnfinic** [comment]
Can I take this?

**Comment by enitrat** [comment]
@elielnfinic sorry i'm seeing this a bit late, but i'll work on this
