### ISSUE TITLE
feat: deploy script needs to update Kakarot storage variables

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1152]
### Describe the Feature Request

The deploy script / update script used to update Kakarot needs not only to update the classes of the deployed contracts, but also modify the storage variables of Kakarot (e.g. account_contract_class_hash, Cairo1Helpers_class_hash)

**Comment by estherbreath** [comment]
Can I work on this please?

**Comment by estherbreath** [comment]
@enitrat I am a Blockchain Developer, and would like to work on this issue.

Below is a summary of how I intend to handle it.

Develop the smart contract to include functionalities for;
setting up token streams
specifying the vesting period and 
managing the distribution of tokens..
Ensure the design is modular and easy to understand.

Develop a suite of tests covering all aspects of the contract, including edge cases and error handling. 

Deploy the contract on a testnet. 
Monitor the deployment process and verify that the contract operates as expected.

**Comment by ClementWalter** [comment]
it's done right @enitrat
