### ISSUE TITLE
feat: arachnid precompile

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1167]
## Feature Request

support arachnid deployer as a precompile

### Describe the Feature Request

flow:
- have arachnid deployer L1 address be a precompile on kakarot
- deploy a replica of arachnid contract at an arbitrary address
- point the precompile to this arbitrary address 
caveats: where is this arbitrary address stored? storage variable? hardcoded? which key deploys this new arachnid?

context:
- we tried to replay the arachnid deployment tx but the responsible EOA for the deployment (preeip155 tx -> we don't have the key to this eoa) is locked in a previous kakarot starknet class hash. we can't proceed with natural flow of preeip155 replay.

future solution:
- when we'll do a state reset, we can delete this precompile and replay the arachnid deployment properly. but currently we want to minimise state resets. this will be retro compatible.

needs further scoping @enitrat

**Comment by enitrat** [comment]
@Eikix giving ownership back after #1174 so that you can trigger the process of updating the code at the arachnid address

**Comment by Eikix** [comment]
> @Eikix giving ownership back after #1174 so that you can trigger the process of updating the code at the arachnid address

what should I do? are there scripts in place to perform the action?
maybe @greged93 is a better person for this specific task

**Comment by greged93** [comment]
I can do it, just need to call the endpoint `write_bytecode` with the owner key?

**Comment by Eikix** [comment]
Maybe we need a clear bullet point list of what to do

**Comment by enitrat** [comment]
Let's come back to this once the upgrade is live

**Comment by ClementWalter** [comment]
@enitrat @greged93 is it good now?

**Comment by enitrat** [comment]
Not yet, will close this after testnet upgrade
