### ISSUE TITLE
dev: profile both cairo0 and cairo1 codebases on a large number of scenarios to identify improvement areas of cairo1 for cairo compiler team to optimize further

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1168]
needs further scoping @enitrat 

cairo0 profiler: mastered and known
cairo1 profiler: https://github.com/software-mansion/cairo-profiler?tab=readme-ov-file#running-pprof

contact @pmagiera for help in telegram

**Comment by enitrat** [comment]
Cairo1 profiler does not seem ready yet

**Comment by ClementWalter** [comment]
@enitrat even without profiler, we should try to extract MWE of codes that we use and is way more expensive in cairo than cairo zero

**Comment by ClementWalter** [comment]
closing this as off topic. cairo1 profiling belongs to ssj codebase and profiling in this codebase is already possible
