### ISSUE TITLE
dev: is_valid_jumpdest re-computes Starknet Address

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1176]
https://github.com/kkrt-labs/kakarot/tree/main/src/kakarot/evm.cairo#L292-L317

`is_valid_jumpdest` re-computes the Starknet address every time it's called. Instead, `code_address` could be of type `model.Address*`, and the starknet address would be computed only once.

**Comment by Josh-121** [comment]
can work on this. Please assign
