### ISSUE TITLE
dev: refund test accounts

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot#1180]
In the end_to_end tests, we deploy 5 accounts based on a `seed = range(5)`. This calls `get_eoa`, which ends up deploying each of the EOA and funding them.

The above flow works fine on a devnet, for local testing on `Katana` for example, but could lead to some issues on staging, as account that are already deployed aren't refunded:
https://github.com/kkrt-labs/kakarot/blob/befcb9339781ffd2df0c84d52d9de2406c1e2d32/kakarot_scripts/utils/kakarot.py#L452-L456

Ideally, we want to fund the address with `(amount - current_balance)` EVEN if the contract is already deployed. This will assure that staging accounts won't ever be out of ETH.

**Comment by adrianvrj** [comment]
Hi, is this open for contribution?

I would love to work on this.
