### ISSUE TITLE
tests: add tests for AccountContract

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1186]
Add __unit__ tests for
- set_nonce
- set_implementation

the unit tests will call the __entrypoints__ (not the library) and verify behavior if
- caller is not the owner (KO)
- OK flow

for `set_implemenation`, don't forget to verify in the Syscall mocks that it was called with the expected parameters

**Comment by fabrobles92** [comment]
Hello, can I contribute to the project creating those unit tests?

**Comment by enitrat** [comment]
Hi, yes, you can follow the model of the existing tests in `tests/src/kakarot/accounts/test_contract_account.py` and `tests/src/kakarot/accounts/test_contract_account.cairo`

**Comment by fabrobles92** [comment]
@enitrat Can I contact you maybe on telegram or discord? I am having a specific issue  bringing up the tests

**Comment by enitrat** [comment]
you can discuss here if you want

**Comment by fabrobles92** [comment]
@enitrat  Seems the CONTRIBUITING.md got updated and now I resolved it :) I will push a draft PR soon for early feedback, thanks!
