### ISSUE TITLE
tests: add unit tests for Kakarot ownable functions

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1201]
Add unit tests for all ownable-related entrypoints of Kakarot. You will follow the flow and structure of existing unit tests, 
https://github.com/kkrt-labs/kakarot/blob/20fb9ea5160889af1a1d65a03df6d100516ea423/tests/src/kakarot/test_kakarot.py#L74-L111

and adapt them to the new tests.

- set_authorized_message_sender
- upgrade
- transfer_ownership
- set_native_token
- set_base_fee
- set_coinbase
- set_prev_randao
- set_block_gas_limit
- set_authorized_cairo_precompile_caller
- set_account_contract_class_hash
- write_account_bytecode
- write_account_nonce
- set_authorized_message_sender

the unit tests will call the entrypoints (not the library) and verify behavior if
  1. caller is not the owner (KO)
  2. OK flow

Don't forget to verify in the Syscall mocks that the OK flows were called with the expected parameters (storage writes called, etc)

**Comment by aniketpr01** [comment]
can i take this @enitrat ?

**Comment by enitrat** [comment]
hey, yes, please read the https://github.com/kkrt-labs/kakarot/blob/main/docs/CONTRIBUTING.md guide before!

**Comment by aniketpr01** [comment]
@enitrat 
Requesting to un-assign this task due to some unpreventable circumstances at my end.
Thank you

**Comment by enitrat** [comment]
Thanks for the letting us know :)

**Comment by rvalenciano** [comment]
Hey @enitrat how are you? can I take a shot on this one?
