### ISSUE TITLE
design: anti-L1-spoofing messaging system

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1229]
## Feature Request

The current Messaging System takes the l1_sender address as the caller of the L2 contract invoked.

This can be an issue if, for example, a L2 contract expects to be invoked in specific conditions by another L2 contract, but ends up being called in other conditions by an L1 contract that would match these conditions.

We need to design a system that prevents this from happening:
- Arbitrum has an offset on all L1 addresses executing messages on L2
- Optimism routes all messages from the XDomainMessenger Contract

**Comment by ClementWalter** [comment]
this requires address collision first right? to be able to have on L1 a contract that has exactly the same address as another on L2

**Comment by obatirou** [comment]
It seems optimism is also using address aliasing for deposits tx (used by the [CrossDomainMessenger](https://github.com/ethereum-optimism/optimism/blob/b6e9a614fb4c3d0f0089d0353f9d3ccc7c0be3df/packages/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L176) 
Deposit tx aliasing [here](https://github.com/ethereum-optimism/optimism/blob/b6e9a614fb4c3d0f0089d0353f9d3ccc7c0be3df/packages/contracts-bedrock/src/L1/OptimismPortal.sol#L562)

see https://specs.optimism.io/protocol/deposits.html#address-aliasing
