### ISSUE TITLE
feat: add a root method to model.Account

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1234]
### Describe the Feature Request

Add a root method to compute the account root.
See reference python implementation
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/state.py
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/trie.py

**Comment by EjembiEmmanuel** [comment]
@ClementWalter I'd love to work on this

**Comment by ClementWalter** [comment]
@EjembiEmmanuel I'm sorry this is part of a bigger change not ready for now, so you can't

**Comment by EjembiEmmanuel** [comment]
No worries!
