### ISSUE TITLE
feat: add `execute_starknet_call` entrypoint to accounts

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1237]
### Describe the Feature Request

The "Cairo Precompiles" system includes an EVM <> Cairo interoperability module that allows you to simply call Cairo contracts from your EVM contracts, using our `CairoLib` library in Solidity.

However, all calls made this way will be executed with _caller_address = kakarot_address_.

In the context of synchronous token bridges, or any use cases that relies on the __STARKNET__ address of an account for arbitrary behavior, we want to be able to keep the context about who __actually__ performs the operation.

Therefore, we want to build a system in which:
- An EVM EOA calls an EVM contract
- The EVM contract calls a Cairo Contract
- The Cairo contract has the Starknet Address corresponding to the EVM EOA as the `caller_address`

### Possible solution

Add an `execute_starknet_call` entrypoint to the account, that takes as input a `contract_address, selector, calldata`, and calls the corresponding contract using a low-level `call_contract_syscall`.
The starknet return_data of that call will be propagated back to the Kakarot precompile system.

**Comment by ClementWalter** [comment]
See #1239
