### ISSUE TITLE
feat: add method to compute storage root

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1243]
### Describe the Feature Request
Add a method `root` to compute the storage root. 
Necessary step before https://github.com/kkrt-labs/kakarot/issues/1234.

For reference: https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/trie.py#L89
List of function to replicate:
1. _prepare_dict
2. patricialize
3. encode_internal_node
4. nibble_list_to_compact
5. bytes_to_nibble_list

`encode_node` is not needed for storage as it is bytes

**Comment by ClementWalter** [comment]
closed in favor of the work on keth
