### ISSUE TITLE
feat: add a Cairo based ERC20.sol contract

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1248]
### Describe the Feature Request

Leverage the CairoLib to deploy a solidity ERC20.sol contract actually being a regular Starknet ERC20.cairo

**Comment by Ejembiii** [comment]
@ClementWalter If this task is still open, I can handle it

**Comment by ClementWalter** [comment]
this is done @enitrat right?

**Comment by enitrat** [comment]
yeah but I should probably add tests for that in this repo? It's in another one for now.
