### ISSUE TITLE
dev: add profiling for solidity loops

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot#1249]
Loops seem to take a lot of steps on execution. I think we can highly optimise them by profiling what takes the more steps in a loop. The below solidity contract can be used as a bench:
```solidity
pragma solidity >=0.8.0;

contract Loop {
    function loop(uint256 max) pure public {
        uint256 val = 0;
        for (uint256 i =0; i<max; i++){
            val += i;
        }
    }
}
```

For reference, the execution of the loop for the above contract currently takes `14_093_197` steps when ran with `max = 400` (check `starkli transaction-receipt 0x142c47b0d4000f9c37490237b36a1e5cdf455b9e2a17cf4fa70974e19a5ecac` on Kakarot Sepolia).

**Comment by elielnfinic** [comment]
Can I take this task?

**Comment by greged93** [comment]
Hey @elielnfinic, I think this would be a little complicated for someone who hasn't yet worked on our repo.

**Comment by elielnfinic** [comment]
Alright @greged93, no problem.
