### ISSUE TITLE
bug: fix `exec_copy` early return when `offset > 2**128`

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1258]
### Kakarot version

In [exec_copy](https://github.com/kkrt-labs/kakarot/blob/b316fd1313262b42dbbf819603e271206830841b/src/kakarot/instructions/environmental_information.cairo#L283) and [exec_extcodecopy](https://github.com/kkrt-labs/kakarot/blob/b316fd1313262b42dbbf819603e271206830841b/src/kakarot/instructions/environmental_information.cairo#L419)

this early return
```
// Offset.high != 0 means that the sliced data is surely 0x00...00
// And storing 0 in Memory is just doing nothing.
if (offset.high != 0) {
    return evm;
}
```

is wrong as it may be still necessary to write `0` to the memory if `memory[dest_offset:dest_offset + size]` is not `[0, ...0]`

This should currently fail

```
Exactly, that is the issue. Consider this pseudocode:
- MSTORE something at offset 0x100
- CALLDATACOPY from offset 0xffff...fff to dest_offset 0x100
```

**Comment by obatirou** [comment]
[exec_extcodecopy](https://github.com/kkrt-labs/kakarot/blob/b316fd1313262b42dbbf819603e271206830841b/src/kakarot/instructions/environmental_information.cairo#L419) is also affected should be fixed
