### ISSUE TITLE
fix: implement overflow checks on on gas operations and values

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1268]
### Describe the Feature Request
See https://github.com/kkrt-labs/kakarot/blob/93cd65e533418d46d8e017a0675cc84f51b216bc/src/kakarot/interpreter.cairo#L883

**Comment by mimiethetechsis** [comment]
@obatirou can I take this?

**Comment by obatirou** [comment]
> @obatirou can I take this?

Hi, thank you for your interest, unfortunately, issues open to contribution have a specific tag `open for contribution`

**Comment by obatirou** [comment]
This issue seems not relevant anymore: 
* checks were added in `execute_from_outside` [here](https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/library.cairo#L250)
* in interpreter 
    *  `intrinsic_gas` is used https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/interpreter.cairo#L882
As in [geth](https://github.com/ethereum/go-ethereum/blob/ebe31dfd5c8c053c098b65eac2ec3070b7f8e9a8/core/state_transition.go#L71) and [reth](https://github.com/paradigmxyz/reth/blob/106a0c7cf7b56104929208d719f8d04274906ed6/crates/transaction-pool/src/validate/eth.rs#L778) `intrinsicGas` is a u64 we could assume intrinsic gas is < 2**128 and use `is_le` instead of `is_le_felt` 
    * the `max_fee` could overflow https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/interpreter.cairo#L901 but as `gas_limit` is < 2 ** 64 (checked added above), it would mean `env.gas_price` > 2 ** 192 which seems not possible (and in [reth](https://github.com/paradigmxyz/reth/blob/106a0c7cf7b56104929208d719f8d04274906ed6/crates/primitives/src/transaction/legacy.rs#L27) it is considered as a 2 ** 128)

What are your thoughts on this @enitrat ?

**Comment by enitrat** [comment]
>  we could assume intrinsic gas is < 2**128 and use is_le instead of is_le_felt

Can this assumption be hardcoded? in geth/reth if intrinsic_gas happens to be >2**64 - 1 the program would overflow, which is not the case here for us


Similarly, gas_price is a variable passed by the user in eth_send_transaction / eth_call. If we assert its value to be at most 2**64-1, then yes, we could use is_le

**Comment by obatirou** [comment]
> > we could assume intrinsic gas is < 2**128 and use is_le instead of is_le_felt
> 
> Can this assumption be asserted? in geth/reth if intrinsic_gas happens to be >2**64 - 1 the program would overflow, which is not the case here for us
> 
> Similarly, gas_price is a variable passed by the user in eth_send_transaction / eth_call. If we assert its value to be at most 2**64-1, then yes, we could use is_le

Make sense thank you. Let's add an assertion for `intrinsic_gas` that is necessary indeed. This will allow us to close this issue 
For `gas_price`, let's do that in an other issue as I am not sure how it is handled in geth and reth and if can make this assumption.

**Comment by obatirou** [comment]
After a second read:
Let's close this issue and create one for removing `is_le_felt` for `intrinsic_gas`

**Comment by obatirou** [comment]
`gas_price` needs to be checked as it is a user input and `let max_fee = gas_limit * env.gas_price;` could overflow as said above

**Comment by obatirou** [comment]
So `gas_price` is send to the interpreter through `execute_from_outside` as `effective_gas_price`
https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/library.cairo#L289

This `priority_fee_per_gas` is either `tx.max_priority_fee_per_gas` or `tx.max_fee_per_gas - block_base_fee`.
https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/library.cairo#L287
But both will be < 2 ** 128 - 1  - `block_base_fee`  due to the checks done in the function
https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/library.cairo#L280
Hence it is possible to safely assume `gas_price` < 2 ** 128 - 1 in interpreter and no checks need to be added.
