### ISSUE TITLE
feat: add block info to python ef test runner

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1274]
### Describe the Feature Request

The ef test runner in [test_kakarot.py](../../blob/main/tests/src/kakarot/test_kakarot.py) doesn't use the block info to patch the Syscall Handler currently.

### What

Use the `block` info to patch, see also the main [ef-test runner](https://github.com/kkrt-labs/ef-tests).

**Comment by juandiegocv27** [comment]
Hi @ClementWalter, i would like to work in this issue, could you give me a little bit of more contex please, and if you assign it to me how can i communicate with you for updates?

**Comment by ClementWalter** [comment]
hey @juandiegocv27 the idea is just to use the native `unittest.mock.patch` to patch the `SyscallHandler` attributes, something like

```
tx = block["transactions"][0]
with (
    patch(SyscallHandler, "caller_address", tx["origin"]),
    SyscallHandler.patch_state(parse_state(test_case["pre"]))
):
    evm, state, gas_used, required_gas = cairo_run(
```

but with all the info

**Comment by juandiegocv27** [comment]
hi @ClementWalter, reading the code and the documentation, with my actual skills in testing with python, I concluded that I can´t do it for the moment

**Comment by juandiegocv27** [comment]
> @juandiegocv27 if you want to give it a try, please do

sure I´ll try. For feedback, where should i contact you?

**Comment by ClementWalter** [comment]
just here

**Comment by juandiegocv27** [comment]
Hi @ClementWalter, Im doing the issue, can you assign it to me please?

**Comment by ClementWalter** [comment]
We don’t assign issues to first time contrib because too many people have just passed by and block issues without actively working on them. But no worries please do push your PR when you’re done and I’ll review it
