### ISSUE TITLE
feat: add eth_chain_id to Kakarot contract

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1276]
### Describe the Feature Request

Add a `@view` function to retrieve the chain_id of Kakarot.
The Kakarot chain_id is actually the underlying Starknet chain id but modulo 2**32. This operation would be better done only once at the Kakarot level.

### What

Add

```
@view
func eth_chain_id{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}() -> (
    chain_id: felt,
) {
    let (tx_info) = get_tx_info();
    let (_, chain_id) = unsigned_div_rem(tx_info.chain_id, 2 ** 32);
    return (chain_id=chain_id);
}
```

to `kakarot.cairo` and use `IKakarot.eth_chain_id` everywhere

**Comment by mimiethetechsis** [comment]
@ClementWalter please can I be assigned to work on this?

**Comment by ClementWalter** [comment]
@mimiethetechsis new contributors don't get assigned so as not to block issues if you eventually don't work on it, but you're welcome to push a PR

**Comment by obatirou** [comment]
Shouldn't the `chain_id` be stored in storage of kakarot if we want to do the operation only once at the Kakarot level ?
With the proposed implementation it will re-execute each time the same operation instead of doing only a read of storage.
