### ISSUE TITLE
feat: add eth_send_raw_transaction entrypoint to kakarot

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1277]
### Describe the Feature Request

Currently, the account is responsible for
1. validating the provided signature against the tx payload
2. decoding the payload
3. performing some gas/balance/chain_id validation 
4. broadcasting the tx to Kakarot.eth_send_transaction

In this latter entrypoint, some other tx validation are made and some assumptions are made on the fact that some other validations have already been done in the Account

https://github.com/kkrt-labs/kakarot/blob/a7af5dec26cea8fd191c8a2e98548ca19de7ee43/src/kakarot/interpreter.cairo#L900

This split is a legacy due to the limitation of the `__validate__` entrypoint.

The goal of this issue is to simplify the flow and have Kakarot entrypoint self sufficient.

### What

- [ ] add an `eth_send_raw_transaction` entrypoint to Kakarot, receiving the (unsigned) raw encoded payload
- [ ] copy the code of `execute_from_outside` from https://github.com/kkrt-labs/kakarot/blob/a7af5dec26cea8fd191c8a2e98548ca19de7ee43/src/kakarot/accounts/library.cairo#L208 up to the end and add it in the body of `eth_send_raw_transaction`
- [ ] `eth_send_raw_transaction` calls `eth_send_transaction` as done before with `IKakarot`
- [ ] remove this part from the account and update the call to `IKakarot` accordingly
- [ ] move the gas_price * gas_limit < sender balance check downward (after in `Interpreter.execute`)
- [ ] (optional) split `Interpreter.execute` in `Interpreter.validate` and `Interpreter.execute`

**Comment by obatirou** [comment]
Trying to figure out how to handle the `pre_eip155_tx`
https://github.com/kkrt-labs/kakarot/blob/a7af5dec26cea8fd191c8a2e98548ca19de7ee43/src/kakarot/accounts/library.cairo#L212

We need the `v` part of the signature to determine if it is a `pre_eip155_tx` and, if it is, we need the `msg_hash` to determine if the tx is authorized by reading the Account storage variable `Account_authorized_message_hashes`.
But with this refactoring we do not have access to those information anymore (only the raw encoded payload is passed). Even the `msg_hash` or `v` is passed, as there would not be verification in `eth_send_raw_transaction`, if this endpoint is open to anyone this could lead to pass arbitrary data to the function hence avoiding checks.
