### ISSUE TITLE
bug: enforce len < 32 in Helpers.split_word

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1278]
### Describe the Feature Request

In [split_words](../../blocb/main/src/utils/utils.cairo), if len > 32, then it's not determined if the decomposition is the one of `value` or `value + k*PRIME`.

### What

- [ ] Raise a cairo error if len >= 32
- [ ] Fix `ec_recover` where we use `32` while it's indeed only 20 requires

```
        let (output) = alloc();
        memset(output, 12, 0);
        Helpers.split_word(recovered_address, 20, output + 21);
```

**Comment by obatirou** [comment]
for the fix `ec_recover`, shouldn't this be 
```
memset(output, 0, 12);
Helpers.split_word(recovered_address, 20, output + 12);
```
-> fill 0 from output to  output + 11 
-> from output + 12 to output + 31 fill address 

Regarding `split_words` function, there is no unit tests for it.  A new one should be added in `test/src/kakarot/utils/test_utils{.cairo, .py}` as part of this issue to ensure the raise is done in case `len > 32`
