### ISSUE TITLE
bug: assert value is 0 at the end of load_bytecode

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1279]
## Bug Report

At the end of [`load_bytecode`](../../blob/main/src/kakarot/accounts/library.cairo), we need to assert that `value` is 0

```
jmp cond if remaining_bytes != 0;

assert value = 0;
let bytecode = cast([fp], felt*);
return (bytecode=bytecode);
```

**Comment by obatirou** [comment]
@ClementWalter 
The fix is trivial (done in [PR here](https://github.com/kkrt-labs/kakarot/pull/1290)) but not sure how to test the fix except with a local test by changing the hint and ensure there is a  raise from the assert.

**Comment by ClementWalter** [comment]
@obatirou I'm thinking about a way to patch hints during the tests, not implemented yet but I can try to do this today
