### ISSUE TITLE
opti: create a custom unsigned_div_rem to reduce step used

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1302]
## Feature Request
Add `unsigned_div_rem` to kakarot utils and inline where possible.
Remplace every mention of `from starkware.cairo.common.math import unsigned_div_rem` by the one created.

**Comment by hakymulla** [comment]
can i work on this?

**Comment by hakymulla** [comment]
@enitrat @obatirou can i create unsigned_div_rem.cairo in kakarot utils folder because of a circular import error in (bytes.cairo and utils.cairo) when i add the unsigned_div_rem function in utils.cairo? or how best to resolve this error?

**Comment by obatirou** [comment]
The idea of this issue is to inline the ˋassert_le`. A benchmark needs to be done to know how many steps would be saved. As it is used a lot in the codebase it could be interesting.
What is the exact circular import error you get ? You cannot import from utils.cairo to bytes.cairo ?
If it is not resolvable, I would suggest to create a new file named `math.cairo` to replicate the structure from starkware.

**Comment by obatirou** [comment]
> @enitrat @obatirou can i create unsigned_div_rem.cairo in kakarot utils folder because of a circular import error in (bytes.cairo and utils.cairo) when i add the unsigned_div_rem function in utils.cairo? or how best to resolve this error?

Hi, thank you for your interest, unfortunately, issues open to contribution have a specific tag `open for contribution`
