### ISSUE TITLE
refactor: remove dead code in test_should_return_evm_address_in_bytes32

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1308]
Not used 
https://github.com/kkrt-labs/kakarot/blob/f17bd946998dad55628e6e120023a2c885d47a82/tests/src/kakarot/precompiles/test_ec_recover.py#L58

**Comment by hakymulla** [comment]
can i work on this?

**Comment by obatirou** [comment]
Dead code still here 
https://github.com/kkrt-labs/kakarot/pull/1320/files#diff-7c2facec19237625de0e362cac7c844baedfcb3a64d3a79f6760fa8b7d4d5461R54
