### ISSUE TITLE
opti: bytes_used_128

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1319]
## Opti:

[bytes_used_128](https://github.com/kkrt-labs/kakarot/blob/a41fe3b3e2f4d77a81028777e37813775b824e55/src/utils/utils.cairo#L693) could be optimized [see ssj implementation](https://github.com/kkrt-labs/kakarot-ssj/blob/3e5b6c8d3e35b13609b5f7fd216b3e12bcdabb01/crates/utils/src/helpers.cairo#L1258-L1280)

**Comment by adrianvrj** [comment]
Hi, is this open for contributors?
If so, can I get assigned?

**Comment by obatirou** [comment]
> Hi, is this open for contributors? If so, can I get assigned?

Hi, thank you for your interest, issues open to contribution have a specific tag `open for contribution`

**Comment by obatirou** [comment]
I do not think this is necessary to tackle this issue as it will not be a significative improvement

**Comment by ClementWalter** [comment]
Closing this as we don't plan to make core cairo zero utils updates unless proven to be significant bottlenecks
