### ISSUE TITLE
bug: failure when running `make setup` or `poetry lock`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1334]
### Kakarot version

kakarot at [7112b36](https://github.com/kkrt-labs/kakarot/commit/7112b36e2c7a6b5b93cbb568a379a5c08761a8cb)

### Current behavior

when updating kakarot at latest main, adding one dev dependency (AWS boto3: `boto3 = "=1.34.155"`), then:
- I'm asked to run `poetry lock` to update the lock file
- Running poetry lock yields: `Failed to clone https://github.com/ethereum/consensus-specs.git at 'd302b35d40c72842d444ef2ea64344e3cb889804', verify ref exists on remote.`

### Expected behavior

I should be able to add a new dev dependency and run `make setup` / `poetry lock` smoothly

### Steps to reproduce

1. Pull latest 
1. Add `boto3 = "=1.34.155"` at the end of the poetry toml under the `[tool.poetry.group.dev.dependencies]` paragraph
1. Run `poetry lock`

**Comment by enitrat** [comment]
could not reproduce after running `poetry add boto3@1.34.155`; no issue
