### ISSUE TITLE
feat: use `sha256` syscall from Cairo1Helpers class

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1335]
see https://github.com/kkrt-labs/kakarot-ssj/pull/813

**Comment by adrianvrj** [comment]
Hey, can I work on this?

**Comment by enitrat** [comment]
Hi @adrianvrj, thank you for your interest.
Only issues marked as such are open for contributions

**Comment by obatirou** [comment]
Seems to be a duplicate from https://github.com/kkrt-labs/kakarot/issues/1311 ?

**Comment by enitrat** [comment]
oops yes, although now it's feasible

**Comment by ClementWalter** [comment]
where should this be used in the current codebase? still relevant?

**Comment by obatirou** [comment]
> where should this be used in the current codebase? still relevant?

It should replace the precompiles sh256 as it is more optimized. It will also reduce the cairo0 code used to rely on the syscall
https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362
