### ISSUE TITLE
dev: benchmark cost of calling Cairo Contracts

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1353]
The cost of calling Cairo contracts is composed of:
- A cost per input value that must be converted from EVM bytes to Cairo felt252
- A cost per output value that must be converted from Cairo felt252 to EVM bytes
- Eventual cost of converting EVM bytes to a human-readable data structure
- The cost of execution of the contract itself (could be negligible).

Benchmark these costs, try to highlight a correlation betwen cost and input/output data and plot the cost per byte/felt

**Comment by ooochoche** [comment]
@enitrat Can I work on this
