### ISSUE TITLE
dev: change error raised for input invalid kakarot precompiles

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1367]
The error raise for input is `outOfBoundsRead` instead of `precompileInputError` 
* https://github.com/kkrt-labs/kakarot/blob/b3f8e1864c410fb35d689cdcad8fc271694e4c86/src/kakarot/precompiles/kakarot_precompiles.cairo#L143
* https://github.com/kkrt-labs/kakarot/blob/b3f8e1864c410fb35d689cdcad8fc271694e4c86/src/kakarot/precompiles/kakarot_precompiles.cairo#L50

**Comment by ScottyDavies** [comment]
@obatirou can i take up this issue?

**Comment by ScottyDavies** [comment]
I can't find the issue on onlydust @obatirou
