### ISSUE TITLE
feat: use `nondet segments.add` to initialize struct with empty new segment

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1369]
### Describe the Feature Request

See this MWE taking 7 steps

```
from starkware.cairo.common.alloc import alloc

struct MyStruct {
    arr_len: felt,
    arr: felt*,
}

func main() {
    let (arr) = alloc();

    tempvar my_struct = MyStruct(arr_len=0, arr=arr);

    return ();
}
```

Using the inlined hints, it's down to 5

```
struct MyStruct {
    arr_len: felt,
    arr: felt*,
}

func main() {
    tempvar my_struct = MyStruct(arr_len=0, arr=cast(nondet %{ segments.add() %}, felt*));

    return ();
}
```

This issue is about investigating places where we would loose these 2 steps in, for example, a loop. If an significant gain is possible, implement.

**Comment by obatirou** [comment]
After a review of the codebase and where this could be applied, this does not seems significant. Notable example are State.init or EVM.init but they are used very sparsely and will not incur a significant gain.

**Comment by ClementWalter** [comment]
ok let's close this then
