### ISSUE TITLE
bug: EVM.charge_gas assume values < RC_BOUND

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1388]
### Kakarot version

After #1323 `EVM.charge_gas` changed from accepting `felt` to assuming that there were `< RC_BOUND`.
However, in some places, this assumption doesn't hold.

### What

The places where we can charge more are places were we compute a dynamic gas based on stack inputs (like CODECOPY, MCOPY, etc.).

We need to early return in them before actually calling the function.

### How

Given the `BLOCK_GAS_LIMIT`, get the maximum memory expansion cost fitting into this limit
- use `from ethereum.shanghai.vm.gas import calculate_memory_gas_cost` in python

Using this MAX_MEMORY_SIZE constant, update the `Gas.memory_expansion_cost_saturated` to return corresponding saturated value if any of `size` or `offset` are above
- keep using first `XXX.high != 0`
- then use `let (q, r) = unsigned_div_rem(XXX.low, MAX_MEMORY_SIZE)` and `if q == 0` early return saturated

When saturating, don't use `EVM.charge_gas` but directly create a reverted EVM

Otherwise, process with computation, knowing that all values < MAX_MEMORY_SIZE, so largely in range_check

**Comment by Gerib0y** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
