### ISSUE TITLE
dev: add safe singleton and create2deployer to our deployment scripts

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1457]
# Feature Request

**Describe the Feature Request**

There is a new RIP for rollups which is to simplify adding a list of important contracts that are factories, namely arachnid, createX, create2deployer and safe singleton.

There are 4 contracts in the RIP, so I think we could add the missing two: https://github.com/ethereum/RIPs/pull/30/files#diff-8fb76c4cfd3e4dc31a49e0ecb56ea00561f0f2af4b4d4353c52b62e95fc6a8bbR39 

**Describe Preferred Solution**

For each tx:
- create constants with signer and full tx as per the other pre eip155
- add their deployment following the others (in `deploy_kakarot.py` or a in to be created `deploy_pre_eip155.py`

**Comment by Eikix** [comment]
Might need further scoping, cc'ing @enitrat

**Comment by enitrat** [comment]
vetoing this as they're just permissioned versions of their trustless counterparts CREATEX and Arachnid proxy
