### ISSUE TITLE
bug: docker

### ISSUE THREAD

**Issue by jbcaron** [kkrt-labs/kakarot#1478]
### Kakarot version

v0.9.1

### Current behavior

- the build fails 
- missing file `poetry.lock`

### Steps to reproduce

```sh
docker build -t kakarot -f ./docker/deployer/Dockerfile .
```

### Related code

```yaml
COPY poetry.lock .
RUN --mount=type=cache,target=/root/.cache poetry install
```

**Comment by ooochoche** [comment]
@jbcaron can I work on this

**Comment by ClementWalter** [comment]
indeed, we forgot to update this when we migrated to uv

**Comment by ClementWalter** [comment]
@ooochoche you can if you are available NOW, but otherwise I'll do later on today

**Comment by ooochoche** [comment]
Alright, let me take a look. I will let you know if I can't.

**Comment by ClementWalter** [comment]
@ooochoche solved already indeed
