### ISSUE TITLE
feat: Upgrade OZ and use Ownable2Step for Coinbase

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1488]
### Describe the Feature Request

`Ownable2Step` is safe as it allows to make sure that the new owner will be able to withdraw funds (because it allows to make sure that the new owner is able to trigger a tx to the contract).

### What

- [ ] Update OZ submodule to the latest audited version (V5.0.2 at the time of writing this issue)
- [ ] Make required changes to existing solidity files so that it builds and works (beware of the updated remappings in the OZ lib itself)
- [ ] Use `Ownable2Step` for `Coinbase.sol` and update end to end tests

**Comment by ooochoche** [comment]
@ClementWalter can I work on this?

**Comment by ClementWalter** [comment]
@ooochoche you can, if you can do it in the next 24h plz go

**Comment by ooochoche** [comment]
Alright I can @ClementWalter
