### ISSUE TITLE
feat: add standard token in the deployment flow

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1489]
### Describe the Feature Request

Since Kakarot is now deployed on Starknet, we want to deploy the corresponding DualVmToken directly.

### What

- [x] Pick the list of token form https://github.com/starknet-io/starknet-addresses/tree/master/bridged_tokens (add the repo as a submodule)
- [x] Add a `deploy_token.py` script that will only do this. Remove the related part from the main `deploy_kakarot.py` script)

**Comment by ShantelPeters** [comment]
Hi @ClementWalter can I work on this ?

**Comment by ClementWalter** [comment]
@ShantelPeters sure if you want and can do it in the next 24h

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ClementWalter** [comment]
done, see #1539
