### ISSUE TITLE
admin: security council multisig

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1516]
The security council will be a multisig: it needs different threshold for signatures depending on the function to call on the protocol handler.
Benchmark existing solution: 
* braavos -> not possible at the moment
* argent -> not possible at the moment
* snapshot 
* custom implementation

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
