### ISSUE TITLE
fee-balancer lambda function

### ISSUE THREAD

**Issue by eugypalu** [kkrt-labs/kakarot#1528]
A cron job that checks the fee dynamics every X minutes and rebalances the fees. Each time the cron job runs, it requests fees from the coinbase contract and verifies that the sum of the relayers' balance plus the fees transferred from the coinbase equals the relayers' initial balance. If necessary, it increases or decreases the fees by a standard percentage.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
