### ISSUE TITLE
bug: non-finalized dictionary in RIPEMD160 allows forging of output[1]

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1561]
## Bug Report

As the dict is never finalized, the prover can set arbitrary values and change the output hash.

## Fix to implement
Call `default_dict_finalize(start, x, 0);` before `let (x) = default_dict_new(0);` to ensure the dict cannot be modified

**Comment by ooochoche** [comment]
@obatirou please, is this open for contribution?

**Comment by ShantelPeters** [comment]
Hello @obatirou can i work on this ?
