### ISSUE TITLE
bug: Underconstrained output in felt_to_bytes_little() allows contract deployments to incorrect addresses[1]

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1563]
## Bug Report

https://github.com/code-423n4/2024-09-kakarot-findings/issues/39

## Fix implementation
Check `bytes_len` do not exceed 31.

**Comment by Pvsaint** [comment]
Hi, please let me handle this issue, as this would be my first open source contribution. I'm a fronted and smart contract developer, proficient in solidity and cairo languages.

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @obatirou
