### ISSUE TITLE
dev: return value of Starknet Messaging should be returned

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot#1583]
In L1KakarotMessaging.sol, `starknetMessaging.sendMessageToL2` and `starknetMessaging.consumeMessageFromL2` are not returned. 
They should be

**Comment by ShantelPeters** [comment]
Can I work on this @obatirou

**Comment by SoarinSkySagar** [comment]
hi @obatirou, can you please elaborate the issue further?

**Comment by obatirou** [comment]
Message is removed with https://github.com/kkrt-labs/kakarot/pull/1623 
Closing
