### ISSUE TITLE
dev: use local `kakarot-ssj` instead of remote release from archived repo

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1596]
With the introduction of `modexp` and `ecpairing`, we need to stop using the old remote repo and start using the local version of kakarot-ssj

Changes since the version we're using right now:
- modexp
- ecpairing
- some optimisation changes discussed internally

Once done

- [ ] enable modexp as `external_precompile`
- [ ] enable ecpairing as `external_precompile`

**Comment by ooochoche** [comment]
@enitrat is this open for contribution

**Comment by enitrat** [comment]
No, can you stop spamming please?

**Comment by enitrat** [comment]
Unplanned: the deployments will keep using the audited code in kakarot-ssj repo.
