### ISSUE TITLE
ci(ssj): fix resources CI [1]

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1597]
resources evolution CI for SSJ fails. Investigate and fix it.

failure example: https://github.com/kkrt-labs/kakarot/actions/runs/11753157805/job/32746375941

**Comment by vitaliypopel** [comment]
I had a great experience with CI pipelines, and I can help you with finding and fixing with failure

**Comment by vitaliypopel** [comment]
I had a great experience with CI pipelines, and I can help you with finding and fixing this failure. I already successfully fixed not only one bug in CI, cause must be deployed in github actions. So I'm familiar with it, wanna work with
