### ISSUE TITLE
dev: initialize_chain_id in deployment scripts if uninitialized

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1629]
Following https://github.com/kkrt-labs/kakarot/pull/1571 we need to add a `try` block in the deployment script where we call `initialize_chain_id`, so that existing deployment's chain_id can be updated

**Comment by SoarinSkySagar** [comment]
May I work on this issue @enitrat?

My approach: I'd add the logic to update existing deployment's chain_id by adding a try block containing the initialize_chain_id function. 

ETA: 2 days

**Comment by enitrat** [comment]
hey, yeah that'd be the right approach, inside `kakarot_deployment.py` but I need it in the next hour sorry
