### ISSUE TITLE
dev: create a BytesLib namespace to create bytes helpers that follow the same naming convention as the EVM

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot#457]
# Dev Request

**Describe the Dev Request**

From @ClementWalter 
> We should strive to use the same naming convention as the EVM ...
> In short, I think that we should once for all create a `BytesLib`, put all these helpers with standard naming conventions and tests, and stop to think about it!

**Describe Preferred Solution**

> 
> * word = `bytes32` = `uint256`
> * `bytes_i_` is the _i_ first bytes from the left:
>   
>   * `bytes31(bytes32)` will drop the right most byte
>   * `bytes1(bytes32)` will keep the left most byte
> * `uint_i_` works the opposite (as uint are big endian)
>   
>   * for example, with no overflow, `uint64(uint256)` = `uint64`
>   * so `uint248(uint256)` will drop the left most byte
>   * `uint8(uint256)` will keep the right most byte
> 
> `bytes` is a `bytes1[]`, ie an array of bytes and consequently should not have any leading or trailing 0s added for padding
> 
> 

**Related Code**

Related code would be the broad category of current Helpers that involve byte arrays, and their usage in code.

**Comment by venkatnetha** [comment]
I would be working on this.

**Comment by ClementWalter** [comment]
Closing as we won't do these cairo 0 improvements
