### ISSUE TITLE
dev: Whitelist project hints

### ISSUE THREAD

**Issue by pedrobergamini** [kkrt-labs/kakarot#459]
# Dev Request
**Describe the Dev Request**
Hints used in the alt_bn128 lib included recently in the project need to be whitelisted by Starkware team.

**Describe Preferred Solution**
N/A.

From @tekkac, this is a repo containing hints to wl:

https://github.com/tekkac/cairo-alt_bn128-g1-precompiles

**Comment by pedrobergamini** [comment]
@abdelhamidbakhta

**Comment by LucasLvy** [comment]
Can you please reduce the list to only the necessary hints that are not already whitelisted

**Comment by ClementWalter** [comment]
@LucasLvy how can we know the list of whitelisted hints?

**Comment by Eikix** [comment]
@pedrobergamini after Tel Aviv, it appears many of the hints we asked to whitelist are not used. 

Could we "reduce" the number of hints we ask to whitelist? @LucasLvy mentioned there are too many and some are not relevant to our PR

**Comment by Eikix** [comment]
Granted we're migrating to Cairo 1.0, there's no longer a need to whitelist hints afaik
