### ISSUE TITLE
feat: UnivswapV2Pair tests

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#468]
# Feature Request

**Describe the Feature Request**

Port and hopefully pass the UniswapV2Pair test.

Original file : https://github.com/Uniswap/v2-core/blob/master/test/UniswapV2Pair.spec.ts
There is WIP PR : https://github.com/sayajin-labs/kakarot/pull/490
Save time and start from here!

**Comment by chirag-bgh** [comment]
Hey @ClementWalter , are you working on this? If not I would like to take this one.

**Comment by ClementWalter** [comment]
> Hey @ClementWalter , are you working on this? If not I would like to take this one.

I’m not plz do! I started a while so pointed to a file you’d better start from but don’t plan to keep doing this myself

**Comment by Eikix** [comment]
Hey @chirag-bgh, are you still planning to work on this issue:)?

**Comment by chirag-bgh** [comment]
> Hey @chirag-bgh, are you still planning to work on this issue:)?

Hey, no I'm not working on this anymore. @ClementWalter unassigned me last month
