### ISSUE TITLE
feat: Handle non deployed contract in EXTCODE_SIZE/HASH/COPY

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#474]
# Feature Request

**Describe the Feature Request**

These opcodes need to check wether there actually exists a contract deployed at the required address.
Before the Accounts refacto, this was done by using the Registry returning 0 for non deployed EVM address.

**Describe Preferred Solution**

There should be a way (a syscall, something) to check if there is a contract at a given felt

**Comment by Eikix** [comment]
Can @karasakalmt work on this?

**Comment by Eikix** [comment]
These opcodes give you an input: an EVM address := 160 bits

You will then get `starknet_address := Accounts.compute_starknet_address(evm_address)`

starknet_address <- felt 

and you need to know if at this specific starknet_address, there is a smart contract or not

**Comment by karasakalmt** [comment]
I can be assigned

**Comment by hurrikaanig** [comment]
#479 is referring to the same issue so I am closing it. I think there is no way to solve this issue for now, we need to wait for a forthcoming update

**Comment by Eikix** [comment]
Thanks @hurrikaanig for your input, 
Quick update on this issue: it is still not possible to do

**Comment by ClementWalter** [comment]
see https://github.com/kkrt-labs/kakarot/issues/719

**Comment by Eikix** [comment]
> see #719

From this issue and PR, is this issue now:
- finished and should be closed
- re-enabled since before we couldn't check if wether there actually existed a contract deployed at an evm address

**Comment by ClementWalter** [comment]
This has been fixed in https://github.com/kkrt-labs/kakarot/pull/720
