### ISSUE TITLE
dev: OpCode Execution Jumps

### ISSUE THREAD

**Issue by karasakalmt** [kkrt-labs/kakarot#487]
While executing the bytecode after every operation execution pc jumps to another operation so while jump executes additional wasted cycles(steps) added. 

Lets say you are running 100 step bytecode if there are 100 different operation there are 99 jumps in between so in the end 199 steps are executed and 99 is wasted.

Solution: Implement an interpreter between bytecode and execution layer or add it on top of it.
An object can be used for this particular reason connecting functions to keys can solve the issue structure would look like
``` 
opCodes(opCode => function)

and shoud execute

opCodes[opCode]
```

**Comment by Eikix** [comment]
Hi @karasakalmt, thanks I remember we talked about this during Starknet - Tel Aviv.
Closing this as we didn't follow up and we're moving forward with the new Cairo migration
