### ISSUE TITLE
build: split python-tests into separated unit-tests and integration tests

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#495]
Currently, 3 or 4 of our tests (the integration UniswapV2 and other solidity based) take most of the time in our test suite.

It would be smart to separate them in another job, named `python-tests-integration` in order to run in parallel from other unit tests.

**Comment by ptisserand** [comment]
Can I work on this one ?

**Comment by Eikix** [comment]
perfect:)!

**Comment by ptisserand** [comment]
Do we already have the list of tests to handle in another job ?

**Comment by ClementWalter** [comment]
There is a caveat with this approach as the coverage will not be accurate anymore. Furthermore, the test are supposed to run in parallel already so I'm not sure we could see any significant changes. I think that what you are trying to do with this PR is to make the long test start ASAP, and this may be the way to go https://stackoverflow.com/a/56595221/4444546

**Comment by Eikix** [comment]
I agree! After investigation, I believe our best bet is to identify the culprit test (one or more tests) that is VERY long and start with it.

**Comment by ptisserand** [comment]
Yes I know that splitting in parallel CI jobs involve to fix the coverage part but I think it's worth to do the split.
I don't believe we will able to run 430 tests (200 units & 230 integrations) in parallel on a single runner instance.

**Comment by ClementWalter** [comment]
the fixture initialization is actually a bug inherited from test refactoring, there is an ongoing issue about this #411

**Comment by ClementWalter** [comment]
interesting resources for prioritizing tests:
- https://docs.pytest.org/en/6.2.x/mark.html#mark
- https://pypi.org/project/pytest-order/
