### ISSUE TITLE
Complete IEth Interface and add comments

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot#507]
# Kakarot Workshop Issue

Level: Easy

Complete the Interface functions for IEth and add detailed comments for the entire namespace:

https://github.com/sayajin-labs/kakarot/blob/286aaea710b22bf78facd5257a9da4b608e68a6e/src/kakarot/interfaces/interfaces.cairo#L17

Details: IEth is the ERC20 token that Kakarot uses internally, and currently we only have 2 functions implemented in the Interface.

**Comment by kasteph** [comment]
Hello! Can I pick this up?

**Comment by dbejarano820** [comment]
Hey, noticed this one is still pending. I'll give it a shot
