### ISSUE TITLE
Add tests that expect "fail" to PUSH1 Opcode

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot#509]
# Kakarot Workshop Issue

Level: Medium

Right now we only have, "ok" tests for PUSH1 Opcode.

For this issue please implement at least 1 extra test where calling PUSH1 would fail or revert.

https://github.com/sayajin-labs/kakarot/blob/286aaea710b22bf78facd5257a9da4b608e68a6e/tests/unit/src/kakarot/instructions/test_push_operations.cairo#L19

(Hint, you can play with Uint256 overflow/underflow , Bytes underflow/overflow)

**Comment by irisdv** [comment]
Can I work on this issue ?
