### ISSUE TITLE
Add tests for eoa intitialization 

### ISSUE THREAD

**Issue by TotalPizza** [kkrt-labs/kakarot#523]
Level: Hard

Create a file called `test_eoa.py` under `tests/unit/src/kakarot/accounts/eoa` and add tests to check that the eoa initialization is done correctly.
The test should pretty much be the same as for the contract account `tests/unit/src/kakarot/accounts/contract/test_contract_account.py`.

For Example there should be a class named:
`class TestExternalyOwnedAccount:`
with a subclass called:
`class TestInitialize:`

As a first step you could start by only implementing a test that ensures that the initialization can only be run once.
(The equivalent test for the contract account is called `test_should_run_only_once` and can be found in the file `test_contract_account.py`.

**Comment by Flydexo** [comment]
Taking it

**Comment by dragan2234** [comment]
hey @TotalPizza can I get assigned to this one?

**Comment by dbejarano820** [comment]
Hey I'm going to go ahead and give this one a shot @ClementWalter @danilowhk
