### ISSUE TITLE
Intializing Kakarot Devnet / Rpc and solidity contract deployment on Kakarot

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot#538]
Create an in-depth tutorial for initializing Kakarot Devnet / Rpc and deploying Smart Contract.

Currently, we have the flow to anyone initialize a Devnet, RPC Node, and now we can have anyone deploy Solidity Smart Contracts on Kakarot.

Create an in-depth tutorial with detailed steps so anyone can deploy their first Solidity contract in Kakarot in less than 5 minutes.

**Comment by ArturVargas** [comment]
Hi @danilowhk can I take this one?

**Comment by danilowhk** [comment]
Assigned

**Comment by ClementWalter** [comment]
Closing as this is "solved" with docker compose
