### ISSUE TITLE
feat: Update EOA Account Abstraction to allow normal Starknet transactions to pass.

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#549]
# Feature Request

**Describe the Feature Request**

Currently, EOA only accepts EVM transactions (legacy or typed envelope). We'll add another step to allow Starknet tx to also pass (Argent or Braavos bound tx).

**Comment by ClementWalter** [comment]
Even though we can think of a trivial basic implementation, at least for enabling an easier interaction with scripts, this question requires to me an extra caution and a joint work with Braavos/Argent teams.

In short, the idea is that a user should be able to use their deployed EOAccount with Braavos/Argent. This would allow:
- solidity dapps deployed in kakarot to accept a Starknet wallet (hence starknet users)
- users to have single wallet with all their funds

I've scheduled meetings with Julien and Yoav to get their thoughts about this
