### ISSUE TITLE
feat: validate nonce in EOAccount

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#555]
# Feature Request

**Describe the Feature Request**

Currently, the `nonce` is not used in the `__validate__` step.

**Describe Preferred Solution**

Add the `nonce` in the return of the `EthTransaction.decode` function and compare it the the calling account nonce.

See:

- https://github.com/sayajin-labs/kakarot/blob/main/src/utils/eth_transaction.cairo
- https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/accounts/eoa/library.cairo

**Comment by StarkFishinator** [comment]
I would like to try to do this one !
