### ISSUE TITLE
feat: Build a multi-arch devnet image in the CI

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#575]
# Feature Request

**Describe the Feature Request**

Currently, the devnet image is not working well on mac m1, due to its x86 arch.

**Describe Preferred Solution**

Use Docker manifest to create a multi-arch image, see:
- https://docs.docker.com/engine/reference/commandline/manifest/#manifest-annotate
- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images
- https://docs.docker.com/build/ci/github-actions/multi-platform/

**Related Code**

- [deployments.yml](../blob/main/.github/workflows/deployments.yml)
- [devnet](../blob/main/docker/devnet)

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by bajpai244** [comment]
@Eikix I guess we can close this, as now we do have a multi-arch image for our devnet.
