### ISSUE TITLE
feat: Add explanation and tutorial (if possible) to the Starknet Book

### ISSUE THREAD

**Issue by omarespejel** [kkrt-labs/kakarot#579]
# Feature Request

**Describe the Feature Request**

- Request to add a small tutorial and explanation on what Kakarot is and how it can be used in the [Starknet Book](https://book.starknet.io/) ([repo](https://github.com/starknet-edu/starknetbook/blob/a0563ab4c369eee206ef993f007356690f40ef8a/chapters/modules/chapter_2/pages/kakarot.adoc#L4))
- No need for original content

**Describe Preferred Solution**

- Include a concise tutorial with:
  1. An introduction to Kakarot
  2. Explanation of its use cases in Starknet
  3. Step-by-step guide on how to use Kakarot

**Describe Alternatives**

- Recommend existing resources on Kakarot with me (TG: espejelomar) so I (or the community) can format the tutorial.

**Related Code**

- Provide relevant code snippets for the tutorial
- Include example(s) of Kakarot usage

**Additional Context**

- Adding this tutorial will help readers learn more about Kakarot and its potential use in Starknet projects
- Promotion of the Starknet Book will further increase the visibility of Kakarot

**If the feature request is approved, would you be willing to submit a PR?**
- Yes

**Comment by ashutosh887** [comment]
@omarespejel 
I would love to work on this issue

**Comment by Eikix** [comment]
I think currently Kakarot isn't in a state where we can expose a tutorial to end users, open to challenge

**Comment by ashutosh887** [comment]
@Eikix 
I believe we should atleast add a `Ecosysem` section in the book where Kakarot can be mentioned!

IDK maybe it already is 😄

**Comment by ashutosh887** [comment]
@Eikix 
Let me know where I can discuss with you more on this?

**Comment by Eikix** [comment]
> @Eikix I believe we should atleast add a `Ecosysem` section in the book where Kakarot can be mentioned!
> 
> IDK maybe it already is 😄

There is already a section that mentions Kakarot in the Starknet book at the moment:)! 
Let's add a tutorial for Kakarot as soon as we're ready for it

**Comment by ashutosh887** [comment]
Sure @Eikix 
Let's close this then 😊

**Comment by Eikix** [comment]
No need, we can keep it open for the next couple of month, with low priority

**Comment by ashutosh887** [comment]
Sure you may keep me on loop 😌👍🏻

**Comment by Eikix** [comment]
Closing this for now! And will prepare documentation in the next months
