### ISSUE TITLE
feat: Use katana instead of the starknet-devnet in the kakarot/devnet image

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#589]
# Feature Request

**Describe the Feature Request**

Currently, the [kakarot devnet image](https://github.com/ClementWalter/kakarot/blob/f08d5ba045c40388af5bc70012eb4c99a117447c/docker/devnet/Dockerfile#L1) is using the starknet-devnet.

We'd like to use katana instead, and to make it multi-arch

**Describe Preferred Solution**

In the Dockerfile, install katana instead, and find a way to store state or run deployment script in the command.
Make it multi-arch

**Comment by bajpai244** [comment]
Aye, Aye Captian 🫡

<image src="https://github.com/kkrt-labs/kakarot/assets/41180869/b315402e-ee78-419e-89ba-5d1f07a5983d" width="250px"  />
