### ISSUE TITLE
feat: make a list of important hints for our precompiles

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#613]
# Feature Request

**Describe the Feature Request**

Current: Starkware VM has access to python runtime -> hints can be arbitrary python (just need to whitelist them to get to testnet)

Soon in Mainnet -> full migration to rust infra: Lambdaclass Rust VM does not have access to python runtime -> hints have to be hardcoded in rust and matched on string (and cairo1 hints are matched as well, but idk how, [investigate](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs#L21C4-L21C4))
references:
- https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/hint_code.rs#L1408
- https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/builtin_hint_processor_definition.rs#L812
- https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/skip_next_instruction.rs#L8C4-L8C4

Plan:
- For Kakarot cairo0 codebase -> we may need to add manually the hints used in our precompiles in cairo-vm code (colocate them with the above example)
- For Kakarot cairo1 codebase -> we'll need to add the hints are libfuncs of cairo1

**Comment by Eikix** [comment]
I believe that implementing hints directly in cairo-vm for the cairo0 codebase is overkill, as we're going to migrate soon.

We need to create a strategy for each precompile for the cairo1 migration:
- implement it in cairo1
- implement it as libfunc
- ask SW to implement it as core libfunc

**Comment by ClementWalter** [comment]
Closing in favor of #856
