### ISSUE TITLE
feat: Validate chain_id in Account

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#618]
# Feature Request

**Describe the Feature Request**

The `chain_id` is currently not validated in the `__validate__` entrypoint.

**Describe Preferred Solution**

Add `chain_id` to the output of `EthTransaction.decode` and validate it

**Related Code**

https://github.com/kkrt-labs/kakarot/blob/e5556e30b7560b8d647899b6dc27bf4b20857f38/src/utils/eth_transaction.cairo#L253

**Additional Context**

`chain_id` is used to prevent from replay attack

**Comment by Kron1749** [comment]
Hey,i could try to do this

**Comment by danilowhk** [comment]
So it seems for "legacy_transactions" Chain_Id is inside "v"

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md


And after EIP 1159 the Chain_Id is on the transaction data:

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md#specification

For legacy transactions, we are already validating the Chain_Id in this line:

https://github.com/kkrt-labs/kakarot/blob/30d4341d93bab39d31dd089e09e19cd408ccc338/src/utils/eth_transaction.cairo#L63

Basically, if Chain_Id is incorrect, v will be incorrect, and "validate" should fail.

For normal transactions(after EIP 1559) we are directly getting the Chain_Id from the raw data and validating in this line:

https://github.com/kkrt-labs/kakarot/blob/30d4341d93bab39d31dd089e09e19cd408ccc338/src/utils/eth_transaction.cairo#L184

(This could be moved to be validated on "validate" function.)

One thing I am still looking into is why we need to append the chain_id during decode legacy_tx:

https://github.com/kkrt-labs/kakarot/blob/30d4341d93bab39d31dd089e09e19cd408ccc338/src/utils/eth_transaction.cairo#L71

could be related to how verify_signature function works, but not so sure.

**Comment by Eikix** [comment]
What is the status of this?

**Comment by Eikix** [comment]
@danilowhk
