### ISSUE TITLE
bug: broken link for FAQ for "Is Kakarot part of the Starknet ecosystem?"

### ISSUE THREAD

**Issue by Kron1749** [kkrt-labs/kakarot#621]
# Bug Report

**Kakarot version:**

main branch

kakarot/Readme.md

**Current behavior:**

When click on "Is Kakarot part of the Starknet ecosystem?"
redirect not to answer,but to newest questions https://www.newton.so/

**Expected behavior:**

Should redirect to the answer page

**Steps to reproduce:**

**Related code:**

**Other information:**

**Comment by Eikix** [comment]
Will remove Newton links
