### ISSUE TITLE
feat: Implement `Invalid` { 0xFE } opcode

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#628]
# Feature Request

We as of now do have the[ implementation](https://github.com/kkrt-labs/kakarot/blob/1bbf0ab9f579e318b74f07ee836657b938e75bba/src/kakarot/instructions/system_operations.cairo#L129) of this opcode, but it is in a TODO phase, where we assert { TRUE=FALSE } and throw an error, but in practice, we should return an [execution context](https://github.com/kkrt-labs/kakarot/blob/1bbf0ab9f579e318b74f07ee836657b938e75bba/src/kakarot/model.cairo#L102), i.e the revert needs to be at the EVM level, not at the Cairo-VM level.

**Describe Preferred Solution**

We have to revert with an execution context, but we do need to do some investigation on the proper way to revert in this scenario by checking some other implementations as well.

**Comment by ashutosh887** [comment]
@bajpai244 Let me work on this issue

**Comment by ashutosh887** [comment]
cc: @Eikix

**Comment by ClementWalter** [comment]
so we should just run exec_revert with 0, 0 instead

> Equivalent to [REVERT](https://www.evm.codes/#FD) (since Byzantium fork) with 0,0 as stack parameters, except that all the gas given to the current context is consumed.

**Comment by Eikix** [comment]
alright @ashutosh887 I'll assign you, here are the tasks:

- modify exec_invalid to behave the same as `exec_revert` 
- use stack returned elements 0,0 as per evm.codes's indication https://www.evm.codes/#fe?fork=shanghai
- change all the affected tests

**Comment by ashutosh887** [comment]
Thanks a lot @Eikix Sir
I'll try to do them all

**Comment by ClementWalter** [comment]
closing this in favor of https://github.com/kkrt-labs/kakarot/issues/766
