### ISSUE TITLE
doc: delete mentions of the account registry in the documentation / readme

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#629]
Starknet addresses fit in 31 bytes
EVM addresses fit in 20 bytes
There needs to be a reconciliation between these two incompatible structures.

Previously:
For maintaining a mapping between EVM and Starknet addresses, we relied on an account registry (smart contract that maintains the 1 to 1 relation).

Currently:
We maintain the mapping by using:
- EVM to Starknet -> `compute_starknet_address` deterministic function that computes the Starknet address of a specific EVM address
- Starknet to EVM -> `get_evm_address` function that fetches from a Starknet contract (must be related to Kakarot) its corresponding EVM address (⚠️ not the same as a troncated address)

Future:
We might reintroduce the account registry, to increase interop and allow any starknet smart contract (smart wallet) to register itself an EVM address.

**Comment by ashutosh887** [comment]
Let me work on this @Eikix

**Comment by ashutosh887** [comment]
@Eikix Can you assign?

**Comment by Eikix** [comment]
My bad! Thanks for pinging me

**Comment by Eikix** [comment]
There you go! Thank you for your commitment

**Comment by ashutosh887** [comment]
Thanks @Eikix

**Comment by Eikix** [comment]
Ideally we'd delete:
https://github.com/kkrt-labs/kakarot/blob/9773e4d10a3c3a32fb8aa3cfbf6fdbff35d6985e/docs/general/kakarot_components.md?plain=1#L7

and then replace the main schema in the readme with one that doesn't revolve around account registry in the flow, such as this one:
![image](https://github.com/kkrt-labs/kakarot/assets/66871571/29f7b729-0da9-448c-92cf-5c19df45a7d4)

**Comment by Eikix** [comment]
What is the status of this @ashutosh887
