### ISSUE TITLE
feat: in eth_call, check that it is only called, never invoked

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#630]
# Feature Request

**Describe the Feature Request**

in eth_call, check that it is only called, never invoked. 

@view and @external decorators on functions cannot actually enforce that some function is only view-called with `starknet_call` or invoked.

**Describe Preferred Solution**

check with get_tx_info() that signature is null, or sender_address is null, or max_fee is 0.

**Describe Alternatives**

this is still a timebox as it's unclear if this is completely sound and sufficient

**Comment by ClementWalter** [comment]
So we can use either `get_caller_address` or `get_tx_info`, not sure if we need both or if one is less informative than the other.

If we just want to make sure we can write a small cairo contract

```
@view
func get_caller_and_tx_info{}(){
    let (caller) = get_caller_address();
    let (tx_info) = get_tx_info():
    return (caller, tx_info);
}
``` 

deploy on testnet and see what we get when we `call` and `invoke`.

I think that using the `caller` will have a side effect that no contract can call, though in `view` `eth_call`, so probably not what we want.

Considering the fact that `tx_info` is a struct such as follows:

```
struct TxInfo {
    // The version of the transaction. It is fixed (currently, 1) in the OS, and should be
    // signed by the account contract.
    // This field allows invalidating old transactions, whenever the meaning of the other
    // transaction fields is changed (in the OS).
    version: felt,

    // The account contract from which this transaction originates.
    account_contract_address: felt,

    // The max_fee field of the transaction.
    max_fee: felt,

    // The signature of the transaction.
    signature_len: felt,
    signature: felt*,

    // The hash of the transaction.
    transaction_hash: felt,

    // The identifier of the chain.
    // This field can be used to prevent replay of testnet transactions on mainnet.
    chain_id: felt,

    // The transaction's nonce.
    nonce: felt,
}
```

we need to check what it returns in a `call` and probably use `account_contract_address`

**Comment by Eikix** [comment]
Do you have bandwith to try it out?

**Comment by ClementWalter** [comment]
can do
