### ISSUE TITLE
bug: deply job is failing

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#631]
# Bug Report

**Kakarot version: 1bbf0ab9f579e318b74f07ee836657b938e75bba**

**Current behavior:**

The current [deploy](https://github.com/kkrt-labs/kakarot/blob/main/.github/workflows/deployments.yml) job is failing, we have to fix this.

**Expected behavior:**

The deploy job should work.

**Steps to reproduce:**

Re-run the latest deploy job.

**Other information:**

- to see the [log](https://github.com/kkrt-labs/kakarot/actions/runs/5487978681/jobs/10064321997).
- this seems to be happening after the Infura testnet outage got fixed; might something happened which is breaking it?

**Comment by Eikix** [comment]
What is the status of this @bajpai244 ?
My understanding is that it can be closed now

**Comment by bajpai244** [comment]
@Eikix yeah in its context it is no longer relevant, closing now.
