### ISSUE TITLE
bug: katana image is failing on build, because dojo asset has been deleted

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#632]
# Bug Report

**Kakarot version: 1bbf0ab9f579e318b74f07ee836657b938e75bba**

**Current behavior:**

The current [Katana image](https://github.com/kkrt-labs/kakarot/blob/main/docker/katana/Dockerfile) is failing because the [dojo assets](https://github.com/kkrt-labs/kakarot/blob/1bbf0ab9f579e318b74f07ee836657b938e75bba/docker/katana/scripts/download_katana.sh#L3) it downloads have been deleted.

**Expected behavior:**

The image should work.

**Comment by Eikix** [comment]
Closing this as it is fixed
