### ISSUE TITLE
feat: Update chainId to 9000

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#652]
# Feature Request

**Describe the Feature Request**

After some insightful discussion with Abdel, Greged, Elias and Steve from ABCDE, we've come to the conclusion that the chainId should be 9000, for obvious reasons.

**Describe Preferred Solution**

Wherever there is b'KKRT', use 9000 instead.

**Describe Alternatives**

No alternative

**Additional Context**

It's over

**Comment by Eikix** [comment]
It's unfortunately already taken by evmos...

https://chainlist.org/?search=9000&testnets=true

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-9000.json

**Comment by ClementWalter** [comment]
> It's unfortunately already taken by evmos...
> 
> https://chainlist.org/?search=9000&testnets=true
> 
> https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-9000.json

EVMOS **testnet** 😤

**Comment by Eikix** [comment]
Closing this for now as 9000 is taken,
b'KKRT' is good enough for now:)
