### ISSUE TITLE
dev: make TestSystemOperations.test_create only nonce 0

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot#653]
We have a [PR](https://github.com/kkrt-labs/kakarot/pull/649) to remove nonce management from the EOA, which means we no more have the ability to [mock nonce](https://github.com/jobez/kakarot/blob/c3c8d802aeec98d064cb2ef855e1247933bfe9fa/tests/src/kakarot/instructions/test_system_operations.cairo#L83) anymore.

As described in #534 , `StarknetContract` uses 0 as a nonce, hence the `[test_create](https://github.com/jobez/kakarot/blob/c3c8d802aeec98d064cb2ef855e1247933bfe9fa/tests/src/kakarot/instructions/test_system_operations.py#L90)` will fail on all of its parameters.

If we test it with nonce 0 it should pass and still allow us to run the test, we will just loose the parameterisation we had over the test.

**Comment by jobez** [comment]
Ok, so basically I think we can do a refactor of this test to no longer assert an expected create address

https://github.com/jobez/kakarot/blob/main/tests/src/kakarot/instructions/test_system_operations.cairo#L702

so we remove the nonce stuff from the test:

https://github.com/jobez/kakarot/blob/main/tests/src/kakarot/instructions/test_system_operations.cairo#L663,

meaning we don't need to pass the arguments of nonce/expected_create_address anymore:

https://github.com/jobez/kakarot/blob/main/tests/src/kakarot/instructions/test_system_operations.cairo#L633

meaning that we want to refactor out the logic in python around nonce/expect_create_address into something that does a unit test against `CreateHelper.get_create_address`: https://github.com/jobez/kakarot/blob/main/src/kakarot/instructions/system_operations.cairo#L816

**Comment by bajpai244** [comment]
@jobez this approach also makes sense, I guess we can do it in the following way:
- to ease the way and limit scope of #649 ,  let's just use nonce 0 for testing
- let's create another issue for this, which can do this refactor as a separate scope after we merge #649.

Lemme know if that works?

**Comment by bajpai244** [comment]
Had a conversation with @jobez, conclusion:
- He will approach his approach in a separate PR { he will create an issue for it soon }
- This issue can be considered resolved with the first appraoch of just using 0 as a nonce to test

**Comment by jobez** [comment]
> Had a conversation with @jobez, conclusion:
> 
> * He will approach his suggestion in a separate PR { he will create an issue for it soon }
> * This issue can be considered resolved with the first approach of just using 0 as a nonce to test

see #654

**Comment by Eikix** [comment]
Closing as #654 is closed
