### ISSUE TITLE
feat: investigate ethereum/tests for Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#660]
Exploration issue: we want to understand how to run ethereum/tests for Kakarot
- is it at rpc level?
- is it at the vm level?
- how to handle state?
- how do others do it? geth besu reth

**Comment by jobez** [comment]
Big picture flow:


![high level diagram](https://github.com/kkrt-labs/kakarot/assets/615197/95ba25ec-daba-4842-a4b0-6ff490aacd88)

Some concrete examples across two projects:


- inclusion of the ethereum tests as a submodule
   - nethermind: https://github.com/NethermindEth/nethermind/blob/master/.gitmodules#L3
   - mana: https://github.com/mana-ethereum/mana/blob/master/.gitmodules#L1
- loading a particular ethereum test json
   - here we have one class per json file https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Ethereum.VM.Test/PerformanceTests.cs#L24
   - this json file is loaded as a `GeneralStateTest` object
     - first loaded:  https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Ethereum.Test.Base/LoadGeneralStateTestsStrategy.cs#L37
     - then converted to an ethereum test: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs#L22 
     - after loaded and coverted to the expected types, it is then ran as follows:  https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs#L50
     - in mana, they use the json as follows: https://github.com/mana-ethereum/mana/blob/master/apps/evm/test/support/evm_test_runner.ex#L10 


We would want to do something like Mana, where we have a top level entrypoint that describes the categories of ethereum tests we want to use and be able to express which tests we expect to pass: https://github.com/mana-ethereum/mana/blob/master/apps/evm/test/evm_test.exs#L10

**Comment by jobez** [comment]
KK, clarified my initial comment that this flow was for the VM case, now digging into how projects use https://ethereum-tests.readthedocs.io/en/latest/retesteth-ref.html

**Comment by Eikix** [comment]
Are all the contents of this issue's comments encapsulated in https://www.notion.so/kakarotlabs/Ethereum-Tests-Research-680d13186ad94da397cdf19acffe7955 ?

If yes, I can close this and let you focus on Scroll
