### ISSUE TITLE
bug: Error when testing revert

### ISSUE THREAD

**Issue by marciob** [kkrt-labs/kakarot#681]
# Bug Report

**Kakarot version:**

**Description:**

While testing the following testCustomError function on a contract it doesn't return the revert message when in error:
```
// Error Contract: Function for demonstrating custom error
function testCustomError(uint _withdrawAmount) public view {
    uint bal = address(this).balance;
    if (bal < _withdrawAmount) {
        revert InsufficientBalance({balance: bal, withdrawAmount: _withdrawAmount});
    }
}
```

I expected a detailed revert message error indicating. However, the error returned is a generic "Contract error" without the additional error details.

**Expected behavior:**

The function should revert with a detailed InsufficientBalance error indicating the current balance and the attempted withdrawal amount when testing passing the value 3, like that:

```
call to Error.testCustomError errored: VM error: revert.
revert
    The transaction has been reverted to the initial state.
Error provided by the contract:
InsufficientBalance
Parameters:
{
 "balance": {
  "value": "0"
 },
 "withdrawAmount": {
  "value": "3"
 }
}
Debug the transaction to get more information.

```

**Actual Behavior:**

But the actual behavior is a generic contract error when calling and passing the value 3:

```
call to Error.testCustomError
call to Error.testCustomError errored: Returned error: {"jsonrpc":"2.0","error":"Contract error","id":8735309095055043}

```

**Steps to reproduce:**

Deploy a contract to the Kakarot ZKEVM blockchain, without balance in the contract, with the `testCustomError` mentioned above.
Call the testCustomError function with an argument of 3 (or other number).

**Other information:**

Additional Information:

EVM environment: Kakarot ZKEVM blockchain (Testnet)
Solidity version: 0.8.17
No balance was sent to the contract upon deployment.

**Comment by Eikix** [comment]
Thanks you for the bug report! 🥕🦾🥷

Can you provide the full code of your contract?

**Comment by marciob** [comment]
> Thanks you for the bug report! 🥕🦾🥷
> 
> Can you provide the full code of your contract?

sure, there is:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract Error {
    function testRequire(uint _i) public pure {
        // Require should be used to validate conditions such as:
        // - inputs
        // - conditions before execution
        // - return values from calls to other functions
        require(_i > 10, "Input must be greater than 10");
    }

    function testRevert(uint _i) public pure {
        // Revert is useful when the condition to check is complex.
        // This code does the exact same thing as the example above
        if (_i <= 10) {
            revert("Input must be greater than 10");
        }
    }

    uint public num;

    function testAssert() public view {
        // Assert should only be used to test for internal errors,
        // and to check invariants.

        // Here we assert that num is always equal to 0
        // since it is impossible to update the value of num
        assert(num == 0);
    }

    // custom error
    error InsufficientBalance(uint balance, uint withdrawAmount);

    function testCustomError(uint _withdrawAmount) public view {
        uint bal = address(this).balance;
        if (bal < _withdrawAmount) {
            revert InsufficientBalance({balance: bal, withdrawAmount: _withdrawAmount});
        }
    }
}

```
