### ISSUE TITLE
bug: Contract with Payable Constructor doesn't deploy when value is provided

### ISSUE THREAD

**Issue by Falco90** [kkrt-labs/kakarot#682]
# Bug Report

**Kakarot version:**

**Current behavior:**

When a value is added to the deploy transaction on a contract with a payable constructor, the contract does not deploy and gets stuck on "pending". When the value is left as 0, the contract deploys normally.
**Expected behavior:**

The contract should deploy with a balance equal to the amount of the transaction. (specified in the "value" field in Remix).
**Steps to reproduce:**

1. Run a Katana RPC locally using Docker
2. Go to Remix and write a contract with a payable constructor:

````
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ReceivableConstructorWithEther {
    uint public balance;

    constructor() payable {
        balance = msg.value;
    }
}
````
Compile, Deploy the contract, and run the function. The error should be:
creation of ReceivableConstructorWithEther pending...

**Related code:**

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ReceivableConstructorWithEther {
    uint public balance;

    constructor() payable {
        balance = msg.value;
    }
}

```

**Other information:**
For reference, I tested the functionality and got the expected behavior with the Remix Shanghai VM, and on the Goerli network.

**Comment by ClementWalter** [comment]
I don't know where we got this from, but we did think that it was not possible to send value to the constructor 🤔😂
