### ISSUE TITLE
bug: Hashing algorithms sha256, ripemd160 and ecrecover don't work as expected

### ISSUE THREAD

**Issue by 0xneves** [kkrt-labs/kakarot#692]
# Bug Report

**Kakarot version:**

816ca4ae6d2123093be01524051fed0431ee6ab2

**Current behavior:**

Op codes: `sha256`, `ripemd160`and `ecrecover` are not being executed by VM.

**Expected behavior:**

Returns the pure execution of each opcode. Below expected results:
![image](https://github.com/kkrt-labs/kakarot/assets/90667119/16b6884c-7cf3-44cf-b462-43f8ac4d43c3)

**Steps to reproduce:**

Setup:

1. Run a local Katana RPC using Docker.
2. Deploy the contract below using Remix with the environment set to "Injected Provider - Metamask".
3. Call each one of the read-only functions.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract HashingForRemix {
    function useKeccak256() public pure returns (bytes32) {
        string memory name = "Blockful";
        bytes memory encodedName = abi.encodePacked(name);
        return keccak256(encodedName);
    }

    function useSha256() public pure returns (bytes32) {
        string memory name = "Blockful";
        bytes memory encodedName = abi.encodePacked(name);
        return sha256(encodedName);
    }

    function useRipemd160() public pure returns (bytes32) {
        string memory name = "Blockful";
        bytes memory encodedName = abi.encodePacked(name);
        return ripemd160(encodedName);
    }

    // signer pkey 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
    // v 27
    // r 0xe56beeb0661820111478c4b6f0435e5e1ee811676153432412b96e5e15056ee4
    // s 0x55b75850e86c0b2a4a56f39ea1f560d6a30517bea27b73b7f537b56cffba3563
    function useEcrecover(
        uint8 v,
        bytes32 r,
        bytes32 s
    ) public pure returns (address) {
        return ecrecover(useKeccak256(), v, r, s);
    }
}
```

**Related errors:**
When calling `sha256`:
![image](https://github.com/kkrt-labs/kakarot/assets/90667119/5c727bf5-1f4f-468b-a51c-cdd96048fe47)

When calling `ripemd160`:
![image](https://github.com/kkrt-labs/kakarot/assets/90667119/5ea61bde-5cab-4e2b-b14f-1ed6051c06eb)

When calling `ecrecover`:
![image](https://github.com/kkrt-labs/kakarot/assets/90667119/12c78571-90aa-41e8-b96f-cd7e0122ec41)

Keccak256 is returning correctly. Above 3 errors from Remix log are listed below:
![image](https://github.com/kkrt-labs/kakarot/assets/90667119/993d4e3c-07a6-4c4d-b6ff-adbb58da77fb)

**Other information:**

**Comment by ClementWalter** [comment]
Closing in favor #856
