### ISSUE TITLE
bug: calling send or transfer to send eth to an deployed EOA results in an error

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#696]
# Bug Report

Bug line:
https://github.com/kkrt-labs/kakarot/blob/ee6458a7089f169334a7dba9665bcc5551507762/src/kakarot/instructions.cairo#L633-L634

`is_caller_eoa` function does not check if the caller is an eoa, but rather if the current execution_context.starknet_address i.e. the `to` field, is the initiator of the original transaction
https://github.com/kkrt-labs/kakarot/blob/ee6458a7089f169334a7dba9665bcc5551507762/src/kakarot/execution_context.cairo#L957

# Context

For Hive testing, a few number of tests require a random EOA address to be funded by a vault contract. A pre-funded vault account initiates this transaction and [sends](https://github.com/kkrt-labs/hive/blob/10ecd48f75d567443ef4a14d0551478a3ddc1492/simulators/ethereum/rpc/vault.go#L172) it to the RPC. This gets forwarded to the Kakarot contract which calls the Vault contract account to trigger [`sendSome`](https://github.com/kkrt-labs/hive/blob/10ecd48f75d567443ef4a14d0551478a3ddc1492/simulators/ethereum/rpc/vault.go#L244) which is supposed to send ether to the receipient (random EOA address). Below is an illustration of this flow.

![image](https://github.com/kkrt-labs/kakarot/assets/35031356/95829050-373f-4b0e-b013-688171480289)

This transaction results in an error of `write_bytecode` (selector `0x02924428227755519d0d1f4c445655beb5ab0661745d485288bffc03b761480e`) being called on the EOA, however this entrypoint doesn't exist in this proxy implementation as it is not a contract account.

```Python
/Users/fredtupas/kkrt-labs/kakarot-rpc/lib/kakarot/src/kakarot/instructions/system_operations.cairo:939:13: (pc=0:17065)
autogen/starknet/contract_interface/IContractAccount/write_bytecode/559d69eb844436aecce68444e3081f5454f64369bacc33810ab7183dac927040.cairo:2:31: (pc=0:1877)

Error in the called contract (0x04ab88e2851193d989cd7d97e2aec2afa7eaa8d9a8d9e6216997eaa5eb80d7b6):
/Users/fredtupas/Library/Caches/pypoetry/virtualenvs/kakarot-fN4XkEXT-py3.9/lib/python3.9/site-packages/starkware/cairo/common/hash.cairo:16:18: Error at pc=0:7:
    let result = hash_ptr.result;
                 ^*************^
Got an exception while executing a hint: Custom Hint Error: Entry point EntryPointSelector(StarkFelt("0x02924428227755519d0d1f4c445655beb5ab0661745d485288bffc03b761480e")) not found in contract.
Cairo traceback (most recent call last):
src/kakarot/accounts/proxy/proxy.cairo:34:6: (pc=0:163)
src/kakarot/accounts/proxy/proxy.cairo:39:48: (pc=0:149)
```

**Comment by ClementWalter** [comment]
possible easy fix for this: add a check in the `return_data_len` https://github.com/kkrt-labs/kakarot/blob/ee6458a7089f169334a7dba9665bcc5551507762/src/kakarot/instructions.cairo#L636
