### ISSUE TITLE
feat: Be able to run a given ethereum foundation BlockchainTest json file as a test

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot#738]
# Feature Request

**Describe the Feature Request**

Introduce the capability to directly reproduce failing test cases from the [Ethereum Foundation tests](https://github.com/ethereum/tests) in the Kakarot v0 Python environment to streamline debugging efforts.

At present, we manually translate test failures from the ef-tests into Kakarot's test system, this adds an extra task to bug triaging that could be simplified.

Example of Current Workflow: [Link to existing test translation](https://github.com/kkrt-labs/kakarot/blob/9f39628f6cde8b8747cdcf1e86c74ffe7fe8ece0/tests/integration/solidity_contracts/EFTests/test_sha3.py#L13-L43)
Reference for Ethereum Test Blockchain Test: [Blockchain Test Format](https://ethereum-tests.readthedocs.io/en/latest/test_filler/blockchain_filler.html#test-structure)

**Describe Preferred Solution**

When a test case (or suite of cases) from the [ef-tests](https://github.com/kkrt-labs/ef-tests) runner fails or produces a runtime error, we want to enable developers to:

- Reproduce the failure for an entire suite (corresponding to a specific JSON file), or
- Reproduce a subset of cases for a particular suite (corresponding to specific keys in the JSON file).
  
 A single case of a suite would be ran as
 ```
 pytest -s ./tests/integration/solidity_contracts/EFTests/debug_runner.py --run VMTests/vmBitwiseLogicOperation/and_d0g0v0_Shanghai
 ``` 
   
We would want to do the same logic we do in [kakarot's ef-tests runner](https://github.com/kkrt-labs/ef-tests) to manipulate starknet state based on the input json and run the tests 'directly' from the json.

An example of manipulating starknet state of the Starknet testing object: https://github.com/0xSpaceShard/starknet-devnet/blob/b9bcd603fc998c6842e3894ad55110ba8f9950d7/starknet_devnet/fee_token.py#L61-L85

An example of how we manipulate the starknet state in blockifier-rust: https://github.com/kkrt-labs/ef-tests/blob/main/crates/ef-testing/src/storage/mod.rs#L37

**Comment by ClementWalter** [comment]
preferred solution is not clear to me : what is the target goal ? how would we like to run the test? do we plan to run file by file or test by test?

**Comment by jobez** [comment]
Updated! I think right now because I see this as mainly benefitting people in the debugging role, we would focus on running either a whole suite of tests in a file or just a subset of cases in a file (with the idea that we are still focusing on cases that presume the Shanghai fork.

Wdyt?

**Comment by ClementWalter** [comment]
the proposed `--run` option would be a custom one? any idea on how to leverage the existing pytest filtering options (`-k` or `-m` for example)?

**Comment by jobez** [comment]
per discussion we will

- have devs manually add relevant json to a particular directory
- use pytest to construct a test for all json in that directory
- have the specific case/suite be callable using standard pytest conventions
