### ISSUE TITLE
bug: `erase_contracts` doesn't completly wipe a contract

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot#764]
### Current behavior
When calling `erase_contracts`, the function only wipes out the bytecode (and the balance is transfered out during the call to `exec_self_destruct`). Nonce and storage are not deleted.

### Expected behavior
`erase_contracts` should also delete the whole storage of the contract as well as the nonce. The nonce is easy but the storage could prove difficult, as it might require us to maintain 2 other storage vars:
```python
@storage_var
func storage_len() -> (res: felt) {
}
@storage_var
func storage_keys_used(index:felt) -> (value: Uint256) {
}
```

**Comment by Eikix** [comment]
This should be fine and could be closed or referenced in other issues when we decide to adopt https://eips.ethereum.org/EIPS/eip-6780

EIP Self destruct only in same transaction 


We have most of the features of the EIP enabled, we just need to check that everything fits the EIP
