### ISSUE TITLE
feat: value field in execution context should be u256, not felt

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#773]
### Describe the Feature Request

- change the field value in the execution context to be a u256, not a felt
- update the codebase where meaningful (we used to split_felt and then cast into u256 where suitable)
- some tests of execution context might need adding a new felt for dw/asserting the initial execution context
- make sure all tests pass

### If the feature request is approved, would you be willing to submit a PR? Yes

/ No _(Help can be provided if you need assistance submitting a PR)_

**Comment by faytey** [comment]
Can i hop on this

**Comment by Eikix** [comment]
> Can i hop on this

sure !

**Comment by Eikix** [comment]
> Can i hop on this

This change might have a lot of downstream changes, this'll take quite a while, since the type will change "everywhere" ->
every single value check, every single creation of context, every test, etc.

**Comment by faytey** [comment]
Okay great, thanks for reaching out, i'd hop right on it and let you know if I need any clarifications

**Comment by faytey** [comment]
Hello @Eikix please can a clearer context of this task be added, am i meant to correct every cairo contract, or just tests or ..., can you please help me understand this task properly, thanks

**Comment by ClementWalter** [comment]
hey @faytey I'm sorry but the codebase is currenly under massive refactoring so not the best time to pick a good first issue.

**Comment by faytey** [comment]
Thank you so much
