### ISSUE TITLE
bug: check depth for create (and call?) < 1024

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#815]
## Bug Report

**Current behavior:**

Currently, we entering a new sub context, we don't check depth < 1024
We know that it's unlucky there'll ever be enough gas to have such depth, but still, we need to check those invariants for specs and ef-tests.

**Expected behavior:**

In create and call, check for depth < 1024

Open to proposal for this:
- an execution context field
- something else

**Comment by ClementWalter** [comment]
See #845
