### ISSUE TITLE
bug: accounts created at previously SELFDESTRUCT don't write bytecode

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#821]
### Current behavior

In `Account.commit`, one uses the `is_register` to check whether one needs to deploy and write bytecode.
However, a previously SELFDESTRUCTed contract is registered but still need to commit its bytecode.

### Expected behavior

Write bytecode

### Related code

Add here a condition:

```
let (registered_len) = IAccount.bytecode_len();
if (registered_len == 0) {
    IContractAccount.write_bytecode(starknet_address, self.code_len, self.code);
}
```

See
https://github.com/ClementWalter/kakarot/blob/4c108731aa7adae1c73853a2ba0e612b9dcf6a51/src/data_availability/starknet.cairo#L170

**Comment by enitrat** [comment]
$\text{contract-account} \land \left( (\neg \text{is-deployed} \land \text{has-code-or-nonce}) \lor (\text{is-deployed} \land \text{has-code-or-nonce} \land \text{deployed-nonce} \neq \text{account-nonce}) \right) \Rightarrow \text{to-deploy}$

$\neg \text{is-deployed} \land \text{to-deploy} \land \text{selfdestruct} \Rightarrow \text{deploy-empty}$

$\text{is-deployed} \land \text{to-deploy} \land \text{selfdestruct} \Rightarrow \text{nothing}$

$\text{is-deployed} \land \text{contract-account} \Rightarrow \text{set-nonce}$

$\text{is-deployed} \land \neg \text{contract-account} \Rightarrow \text{nothing}$

I think this covers all commitment cases
