### ISSUE TITLE
feat: use keccak builtin for keccak hashed

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#874]
### Describe the Feature Request

Since Feb 2023, the Cairo VM integrates a keccak builtin. This builtin can be used in Cairo Zero, and the API functions we can use are defined [here](https://github.com/starkware-libs/cairo-lang/commits/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/cairo/common/builtin_keccak/keccak.cairo).

[ ] Replace all existing uses of non-builtin keccak inputs with usage of the keccak builtin

**Comment by enitrat** [comment]
Two ongoing blockers:
- Hint used by the `keccak` function is not whitelisted
- KeccakBuiltin cant be used in Cairo0 contracts entrypoints

**Comment by enitrat** [comment]
After discussing with the SW team, the solution would be to:
- Deploy a `KeccakLibrary` class, written and compiled with Cairo
- Replace all invokes of keccak with library_calls to this `KeccakLibrary` class

**Comment by ClementWalter** [comment]
See #966
