### ISSUE TITLE
bug: gas_limit lower than intrinsic gas should not increase sender nonce

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#956]
### Kakarot version
In Geth https://github.com/ethereum/go-ethereum/blob/16ce7bf50fa71c907d1dc6504ed32a9161e71351/core/state_transition.go#L432-L436 the nonce of the sender is only increased after a check that the gas_limit of the tx is higher than the intrinsic gas. Otherwise, the execution of transaction doesn't even begin and the nonce is not increased.

Globally, in these following cases, the validation should fail and the nonce should not be increased:
```
	// 1. the nonce of the message caller is correct
	// 2. caller has enough balance to cover transaction fee(gaslimit * gasprice)
	// 3. the amount of gas required is available in the block
	// 4. the purchased gas is enough to cover intrinsic usage
	// 5. there is no overflow when calculating intrinsic gas
	// 6. caller has enough balance to cover asset transfer for **topmost** call
```

**Comment by enitrat** [comment]
What has been done for now: 
- Emitted a special error message, returned as return data
- This message is handled by the EF-Test runner to validate tests, even though the nonce is increased.

**Comment by ClementWalter** [comment]
@obatirou check that with #1240 this is solved plz

**Comment by obatirou** [comment]
With current #1240 implementation, the execution will begin anyway (as the intrinsic gas is still calculated in the interpreter).
There is also no overflow checks when calculating the intrinsic gas for now.
But the nonce should not be increased anymore. I will look into ef-test runner where the test validation is done with special error message and modify to check the nonce.

**Comment by obatirou** [comment]
This line is where the validation is done in the ef-test runner [here]( https://github.com/kkrt-labs/ef-tests/blob/ccd904208368d553eed689ecbdedb3e3596c1ea3/crates/ef-testing/src/models/case.rs#L196)
(thank you @enitrat for the pointer)

This should be modified to ensure tests are still passing without it. It will impact ssj tests and this change should be tracked in the ssj repo

Note: intrinsic gas is still calculated in the interpreter [here](https://github.com/kkrt-labs/kakarot/blob/5587a082f8fb23a8a12a1872d56deea04316318c/src/kakarot/interpreter.cairo#L889)
