### ISSUE TITLE
feat: ensure transaction inputs are in range [0, 2e128]

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#961]
### Describe the Feature Request

The calldata passed can be huge and calculating the intrinsic cost for that will overflow PRIME and wrap back to 0.
To avoid these situations where gas is not accounted for correctly, user inputs should be verified to not be above the accepted limits. By checking they're in range [0,2**128], we could avoid these issues.

There are //TODO related to this issue in interpreter.cairo

**Comment by AryanGodara** [comment]
@enitrat Can you please assign this issue to me :)

**Comment by enitrat** [comment]
Calldata limited to 24k by SN parameters, no longer relevant
